# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title                       : Sabrina Rinaldi
email                       : info@sabrinarinaldi.com
description                 : >- # this means to ignore newlines until "baseurl:"
  Wildlife Artist
baseurl                     : "" # the subpath of your site, e.g. /blog
#url                         : "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown                    : kramdown
theme                       : sabrinarinaldi
plugins                     :
    - jekyll-minifier
    - jekyll-email-protect

# Overrides
destination                 : public
source                      : src
permalink                   : /:title.html
sass                        :
  sass_dir                  : _sass
  style                     : compressed

# Collections
collections                 :
  pages                     :
    output                  : true
  critiques                 :
    output                  : false
collections_dir             : collections

# Plugin config
jekyll-minifier             :
  remove_intertag_spaces    : true
  compress_javascript       : false
  exclude                   : ['\*.txt','\*.xml']

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude                     :
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - package-lock.json
  - node_modules
  - src/
